name: quiknowte
description: ... 
author: AGUTU SAM <agutusam@writeme.com>
homepage: https://github.com/AgutuSam/quiknowte.git

version: 1.2.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  open_file: ^3.0.1
  path_provider: ^1.6.5
  permission_handler: ^4.3.0
  http: ^0.12.0+1 
  cached_network_image: ^1.1.1
  sqfentity: ^1.2.0+6
  sqfentity_gen: ^1.1.0+4
  toast: ^0.1.5
  fluttertoast: ^3.1.3
  charts_flutter: ^0.8.1
  flutter_screenutil: ^1.0.2
  font_awesome_flutter: ^8.5.0
  flutter_custom_clippers: ^1.1.0
  image_picker: ^0.6.5+2
  shifting_tabbar: ^0.3.1
  pdf: ^1.6.2
  typicons_flutter: ^0.3.1
  flutter_share: ^1.0.2+1
  flutter_datetime_picker: ^1.3.8
  datetime_picker_formfield: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0   
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  stats: ^1.0.0
  wave: ^0.0.8
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  firebase_storage: ^3.1.6

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  #sqfentity_gen: ^1.0.3+5
  build_runner: ^1.6.5
  build_verify: ^1.1.0
  
  
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4+5
  flare_flutter: ^1.7.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/chinook.sqlite
    - line.png
    - windows-wallpaper.jpg
    - no-picture.png
    - files.jpg
    - blue.jpg
    - wheel.jpg
    - question.jpg
    - assets/img/quiknowte.flr
    - assets/flareintro.flr
    - assets/img/quiknowte-name.flr
    - assets/beach.png
    - assets/projects.png
    - assets/cloud.png
    - assets/element.png
    - assets/penguin.png
    - assets/math.jpg
    - assets/party.png
    - assets/bubble.png
    - assets/origami1.png
    - assets/origami2.png
    - assets/origami3.jpg
    - assets/charts/axes/
    - assets/charts/bar_charts/
    - assets/charts/combo_charts/
    - assets/charts/legends/
    - assets/charts/line_charts/
    - assets/charts/pie_charts/
    - assets/charts/scatter_plot_charts/
    - assets/charts/time_series_charts/
    
  
  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
          style: normal
    
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Thin.ttf
          style: normal
          
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
   
           
              
